# Generated by Django 4.2.7 on 2023-12-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='workflow_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
