# Generated by Django 4.2.7 on 2023-12-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_workflow_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('hiring_manager', 'Hiring Manager')], default=1, max_length=50),
        ),
    ]
