# Generated by Django 4.2.7 on 2023-12-27 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendlyLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('link', models.URLField(verbose_name='Calendly Link')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_calendly_link', to=settings.AUTH_USER_MODEL)),
                ('hiring_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_calendly_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendly Link',
                'verbose_name_plural': 'Calendly Links',
                'db_table': 'core_calendly_link',
            },
        ),
    ]
