# Generated by Django 4.2.7 on 2023-11-21 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('workflow_id', models.CharField(max_length=150)),
                ('job_status', models.CharField(choices=[(1, 'Open (default)'), (3, 'On Hold'), (8, 'Approved'), (7, 'Needs Approval'), (2, 'Drafting'), (4, 'Filled'), (5, 'Canceled'), (6, 'Closed')], default=1, max_length=10)),
                ('minimum_experience', models.CharField(choices=[(1, 'Student (High School)'), (2, 'Student (College)'), (3, 'Entry Level'), (4, 'Mid Level'), (5, 'Experienced'), (6, 'Manager/Supervisor'), (7, 'Senior Manager/Supervisor'), (8, 'Executive'), (9, 'Senior Executive')], default=1, max_length=10)),
                ('canned_felony', models.CharField(choices=[(0, 'Not Selected, Not Required'), (1, 'Selected, Not Required'), (2, 'Selected, Required')], default=0, max_length=10, verbose_name='Felony Conviction')),
                ('canned_education', models.CharField(choices=[(0, 'Not Selected, Not Required'), (1, 'Selected, Not Required'), (2, 'Selected, Required')], default=0, max_length=10, verbose_name='Highest Education Obtained')),
                ('approved_salary_range_minimum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum salary')),
                ('approved_salary_range_maximum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Salary')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_jobs', to=settings.AUTH_USER_MODEL)),
                ('hiring_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'job_jobs',
            },
        ),
    ]
