# Generated by Django 4.2.7 on 2023-11-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='canned_education',
            field=models.CharField(choices=[('0', 'Not Selected, Not Required'), ('1', 'Selected, Not Required'), ('2', 'Selected, Required')], default=0, max_length=10, verbose_name='Highest Education Obtained'),
        ),
        migrations.AlterField(
            model_name='job',
            name='canned_felony',
            field=models.CharField(choices=[('0', 'Not Selected, Not Required'), ('1', 'Selected, Not Required'), ('2', 'Selected, Required')], default=0, max_length=10, verbose_name='Felony Conviction'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('1', 'Open (default)'), ('3', 'On Hold'), ('8', 'Approved'), ('7', 'Needs Approval'), ('2', 'Drafting'), ('4', 'Filled'), ('5', 'Canceled'), ('6', 'Closed')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='minimum_experience',
            field=models.CharField(choices=[('1', 'Student (High School)'), ('2', 'Student (College)'), ('3', 'Entry Level'), ('4', 'Mid Level'), ('5', 'Experienced'), ('6', 'Manager/Supervisor'), ('7', 'Senior Manager/Supervisor'), ('8', 'Executive'), ('9', 'Senior Executive')], default=1, max_length=10),
        ),
    ]
