# Generated by Django 4.2.7 on 2023-12-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='workflow_id',
        ),
        migrations.RemoveField(
            model_name='jobtemplate',
            name='workflow_id',
        ),
    ]
