# Generated by Django 4.2.7 on 2023-11-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_canned_education_alter_job_canned_felony_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('1', 'Full Time'), ('2', 'Part Time'), ('3', 'Part Time to Full Time'), ('4', 'Temporary'), ('5', 'Temporary to Full Time'), ('6', 'Contracted'), ('7', 'Contracted to Full Time'), ('8', 'Internship'), ('9', 'Internship to Full Time'), ('10', 'Volunteer'), ('11', 'Seasonal')], default=1, max_length=10),
        ),
    ]
