# Generated by Django 4.2.7 on 2023-11-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_id',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
