# Generated by Django 4.2.7 on 2023-11-22 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0004_job_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
