# Generated by Django 4.2.7 on 2023-11-28 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_hiring_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('job.job',),
        ),
    ]
