# Generated by Django 4.2.7 on 2023-11-28 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('job.job',),
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
