# Generated by Django 4.2.7 on 2023-12-03 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0009_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnockoutCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('minimum_experience', models.CharField(choices=[('experience1', 'Experience 1'), ('experience2', 'Experience 2')], max_length=50)),
                ('job_description_option', models.CharField(choices=[('template', 'Template'), ('manual', 'Manual')], max_length=50)),
                ('manual_job_description', models.TextField(blank=True)),
                ('education_level', models.CharField(blank=True, max_length=50)),
                ('multiple_languages', models.BooleanField(default=False)),
                ('no_college', models.BooleanField(default=False)),
                ('felon', models.BooleanField(default=False)),
                ('no_references', models.BooleanField(default=False)),
                ('not_citizen', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_criteria_knockout', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_criteria_knockout', to='job.job')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_criteria_knockout', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
