# Generated by Django 4.2.7 on 2023-12-03 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0010_knockoutcriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitleTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('description', models.TextField()),
                ('skills', models.TextField()),
                ('suggested_experience', models.CharField(max_length=50)),
                ('suggested_minimum_education', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_job_title_template', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_job_title_template', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
