# Generated by Django 4.2.7 on 2023-12-08 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0011_jobtitletemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestlifyLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('link', models.URLField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_testlify_link', to=settings.AUTH_USER_MODEL)),
                ('job_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testlify_links', to='job.job')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_testlify_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Testlify Link',
                'verbose_name_plural': 'Testlify Links',
                'db_table': 'job_testlify_link',
            },
        ),
    ]
