# Generated by Django 4.2.7 on 2023-12-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_testlifylink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlifylink',
            name='link',
            field=models.URLField(verbose_name='Job Link'),
        ),
    ]
