# Generated by Django 4.2.7 on 2023-12-08 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0013_alter_testlifylink_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlifylink',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_testlify_link', to=settings.AUTH_USER_MODEL),
        ),
    ]
