# Generated by Django 4.2.7 on 2023-12-15 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('applicant_id', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('prospect_phone', models.CharField(max_length=255)),
                ('apply_date', models.DateField(auto_now_add=True)),
                ('current_position', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('rating', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'db_table': 'applicant_applicants',
            },
        ),
    ]
