# Generated by Django 4.2.7 on 2023-11-23 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='rating',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
