# Generated by Django 4.2.7 on 2023-12-15 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0001_initial'),
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_jobs', to='job.job'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='IdealCandidate',
            fields=[
            ],
            options={
                'verbose_name': 'Ideal Candidates',
                'verbose_name_plural': 'Ideal Candidates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('applicant.jobapplicant',),
        ),
    ]
