# Generated by Django 4.2.7 on 2023-12-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
