# Generated by Django 4.2.7 on 2023-12-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_jobapplicant_city_jobapplicant_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='current_position',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='apply_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
