# Generated by Django 4.2.7 on 2023-12-02 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_jobapplicant_current_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Ideal Candidates',
                'verbose_name_plural': 'Ideal Candidates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('applicant.jobapplicant',),
        ),
    ]
