# Generated by Django 4.2.7 on 2024-01-18 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_canned_citizen_alter_job_canned_college_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant', '0004_remove_jobapplicant_job_jobapplicant_applied_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplicant',
            old_name='rating',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='jobapplicant',
            old_name='status',
            new_name='eeoc_disability_signature',
        ),
        migrations.RemoveField(
            model_name='jobapplicant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='jobapplicant',
            name='current_position',
        ),
        migrations.RemoveField(
            model_name='jobapplicant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobapplicant',
            name='start_date',
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='can_work_evenings',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No answer', 'No answer')], default='No answer', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='can_work_overtime',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No answer', 'No answer')], default='No answer', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='can_work_weekends',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No answer', 'No answer')], default='No answer', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='citizenship_status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No answer', 'No answer')], default='No answer', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='college_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='desired_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Desired Salary'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='desired_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='education_level',
            field=models.CharField(choices=[('High School', 'High School'), ("Bachelor's", "Bachelor's"), ("Master's", "Master's"), ('Ph.D.', 'Ph.D.'), ('No answer', 'No answer')], default='No answer', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='eeo_disability',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EEO Disability'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='eeo_gender',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EEO Gender'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='eeo_race',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EEO Race'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='eeoc_disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='eeoc_disability_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='eeoc_veteran',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='felony_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='has_cdl',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No answer', 'No answer')], default='No answer', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='has_driver_license',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No answer', 'No answer')], default='No answer', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='has_felony',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No answer', 'No answer')], default='No answer', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='languages',
            field=models.TextField(blank=True, null=True, verbose_name='Languages'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn Url'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='over_18',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No answer', 'No answer')], default='No answer', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='referrer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Referrer'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='resume_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='source',
            field=models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('OTHER', 'Other')], default='LINKEDIN', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='willing_to_relocate',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No answer', 'No answer')], default='No answer', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='wmyu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='applied_jobs',
            field=models.ManyToManyField(blank=True, related_name='applicants_jobs', to='job.job'),
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='apply_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JobApplicantMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('comm_id', models.CharField(max_length=255)),
                ('comm_subject', models.CharField(max_length=255)),
                ('comm_text', models.TextField()),
                ('comm_author_email', models.EmailField(max_length=254)),
                ('comm_to', models.EmailField(max_length=254)),
                ('comm_cc', models.EmailField(blank=True, max_length=254, null=True)),
                ('comm_bcc', models.EmailField(blank=True, max_length=254, null=True)),
                ('comm_datetime_sent', models.DateTimeField()),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='applicant.jobapplicant')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Applicant Communication',
                'verbose_name_plural': 'Applicant Communications',
                'db_table': 'applicant_applicant_communications',
            },
        ),
        migrations.CreateModel(
            name='JobApplicantFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('feedback', models.TextField()),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='applicant.jobapplicant')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Applicant Feedback',
                'verbose_name_plural': 'Applicant Feedbacks',
                'db_table': 'applicant_applicant_feedbacks',
            },
        ),
        migrations.CreateModel(
            name='JobApplicantComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('comment', models.TextField()),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='applicant.jobapplicant')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Applicant Comment',
                'verbose_name_plural': 'Applicant Comments',
                'db_table': 'applicant_applicant_comments',
            },
        ),
        migrations.CreateModel(
            name='JobApplicantActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('activity_id', models.CharField(max_length=255)),
                ('activity_on', models.DateTimeField(blank=True, null=True)),
                ('activity', models.TextField()),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='applicant.jobapplicant')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Applicant Activity',
                'verbose_name_plural': 'Applicant Activities',
                'db_table': 'applicant_applicant_activities',
            },
        ),
    ]
