# Generated by Django 4.2.7 on 2024-01-18 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0006_alter_job_canned_citizen_alter_job_canned_college_and_more'),
        ('applicant', '0005_rename_rating_jobapplicant_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplicant',
            name='applied_jobs',
        ),
        migrations.CreateModel(
            name='JobApplicantAppliedJobs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('hiring_lead_rating', models.CharField(max_length=255)),
                ('average_rating', models.CharField(max_length=255)),
                ('applicant_progress', models.CharField(max_length=255)),
                ('workflow_step_id', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='applicant.jobapplicant')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='job.job')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Applicant Applied Job',
                'verbose_name_plural': 'Applicant Applied Jobs',
                'db_table': 'applicant_applicant_applied_jobs',
            },
        ),
    ]
