# Generated by Django 4.2.7 on 2024-01-18 22:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0006_alter_job_canned_citizen_alter_job_canned_college_and_more'),
        ('applicant', '0006_remove_jobapplicant_applied_jobs_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApplicantAppliedJobs',
            new_name='JobApplicantAppliedJob',
        ),
    ]
