# Generated by Django 4.2.7 on 2024-01-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_jobapplicant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicantappliedjob',
            name='workflow_step_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
